### PR TITLE
Make it compatible with py3

### PR DESCRIPTION
**Pull request by naegi**
Make it compatible with py3 but port is not finished: 
- ~~raw_input is now remplaced by input (not safe with py2)~~
- etc.

### CODE REVIEW

**Comment by davydany** [comment]
@naegi this is awesome! Thank you! Can you add the following python version to `.travis.yml`?

```
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
```

as per: https://docs.travis-ci.com/user/languages/python/

this way, we can have Travis build your new changes. And if they all pass, I'll merge it.

Again, thank you so much!

**Comment by naegi** [comment]
Tests don't works for python 3.2 & 2.6
For python 3.2 I really don't know why, but it looks like a bug in the coverage package.
But for python 2.6 it's just an incompatibility between unittest for python 2.6 and uninttest for python 2.7

**Comment by davydany** [comment]
yeah that's fine by me... please remove 2.6 and 3.2 from the yaml, and commit it. I'll merge it once the build passes. 

Honestly, thank you so much for what you did!

**Comment by davydany** [comment]
👍 Looks good to me! Thank you!

**Pull request merged**
